version: '3'

volumes:
  pg_project:


services:

  php:
    build:
      context: ./fpm
      dockerfile: Dockerfile
    image: otus/php-${APP_NAME}
    container_name: php_${APP_NAME}
    volumes:
       - ./code:/data
    networks:
      - app-network
    environment:
      APP_NAME: ${APP_NAME}

  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: otus/nginx-${APP_NAME}
    container_name: webserver_${APP_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - ./code:/data/
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
    volumes:
      - pg_project:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge